name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [ "master" ] # branch to trigger deployment
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Package/doc"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: Package/doc/build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/head/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /